package config

const (
	AppName       = "SingBoxTray"
	RegStateKey   = `Software\SingBoxTray`
	SingBoxExe    = "sing-box.exe"
	SingBoxConfig = "config.json"
	LogFileName   = "tray-sing-box.log"

	// Monitoring
	StatusCheckInterval = 2 // seconds
	// Seconds to wait for the taskbar before creating the tray icon anyway.
	// Long on purpose: nothing but the icon waits for it (the VPN restore
	// runs independently), and registering into a taskbar that exists is
	// cleaner than relying on the tray library's background retries. The
	// timeout remains for alternative shells that have a tray but no
	// Shell_TrayWnd.
	ExplorerWaitTimeout = 600

	// State restore at startup
	RestoreStartAttempts = 3 // how many times to try starting sing-box
	RestoreCheckDelay    = 3 // seconds to wait before verifying it survived
	RestoreRetryDelay    = 2 // seconds between attempts

	// Connectivity check (is traffic actually flowing while VPN is running)
	ConnectivityCheckInterval = 30 // seconds between probes
	ConnectivityStartupDelay  = 10 // seconds after start before the first probe

	// Config history (every config.json save archives the previous version)
	ConfigHistoryDir  = "config-history" // next to config.json
	ConfigHistoryKeep = 20               // versions kept, oldest pruned

	// Crash auto-restart (monitor restarts sing-box whenever it is down while
	// the stored intent is "running" — also after a failed restore at boot)
	AutoRestartMaxAttempts = 5  // consecutive attempts before giving up
	AutoRestartBackoff     = 5  // seconds; the wait after attempt N is N*backoff
	AutoRestartResetAfter  = 60 // seconds of uptime that reset the counter

	// Starting / stopping sing-box
	StartGraceMs        = 1500 // a process that exits within this time is a failed start
	StartErrorTailBytes = 2000 // how much of sing-box's output goes into that error
	StopWaitTimeout     = 5    // seconds to wait for the killed process to disappear

	// sing-box stdout/stderr capture, next to the exe. Bounded by LogMaxSizeMB:
	// rotated when sing-box is started, trimmed in place while it keeps running
	SingBoxConsoleLog     = "sing-box-console.log"
	ConsoleLogTrimMinutes = 30 // how often the size is checked while running

	// Log rotation (tray app log: checked once at startup)
	LogMaxSizeMB = 10 // a bigger log is renamed to <name>.old

	// Subscriptions
	SubscriptionsFileName    = "subscriptions.json" // next to the exe
	SubscriptionRefreshHours = 6                    // periodic auto-refresh interval
	SubscriptionStartupDelay = 60                   // seconds after start before the first auto-refresh

	// Settings web UI sessions. The page is opened with a one-time login code
	// (its URL is readable by any program of the user: browser and rundll32
	// command lines, browser history); the code is traded for a session held
	// only in the memory of the page it opened
	WebLoginCodeSeconds   = 120 // an unused login code expires
	WebSessionIdleMinutes = 30  // a session unused this long expires
	WebSessionMaxHours    = 12  // a session expires this long after the login anyway

	// Self-update of this application from its GitHub releases. Disabled
	// while either value is empty: the app runs elevated and downloads code
	// it then executes, so a release is only accepted when checksums.txt is
	// signed with the key generated by `go run ./tools/relkey` — offline, by
	// the maintainer, never by CI (see .github/workflows/release.yml). Fill
	// in once the repository exists; release.yml refuses to build while empty.
	AppUpdateRepo         = "4Roman/tray-sing-box"                         // GitHub "owner/name"
	AppUpdatePublicKey    = "l7Hwu+fZsSQANqEOYXv2eKRstkGM1EzH/dFrLzN/IwU=" // base64 ed25519 public key
	AppUpdateCheckHours   = 24                                             // background check interval
	AppUpdateStartupDelay = 120                                            // seconds after start before the first check
	AppExeName            = "tray-sing-box.exe"

	// DPI bypass (zapret running in a Docker container)
	DPIImage          = "8hrsk/zapret-docker-proxy:latest"
	DPIContainerName  = "singbox-dpi"
	DPIProxyHost      = "127.0.0.1"
	DPIProxyPort      = 3128
	DPIBypassTag      = "dpi-bypass"     // reserved outbound tag in config.json
	DPIParamsFileName = "dpi-params.txt" // optional ZAPRET_PARAMS, in the data dir
)
